FROM debian:latest

# Instalar vsftpd y otros paquetes necesarios
RUN apt-get update && \
    apt-get install -y vsftpd ftp openssh-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Crear directorios necesarios
RUN mkdir -p /ftp/publico && \
    chmod 755 /ftp && \
    chmod 755 /ftp/publico && \
    mkdir -p /var/run/vsftpd/empty && \
    chmod 755 /var/run/vsftpd/empty

# Crear archivo de ejemplo
RUN echo "Bienvenido al servidor FTP de Desarrollo" > /ftp/publico/README.txt


# Configuración de vsftpd
COPY vsftpd.conf /etc/vsftpd.conf
RUN chmod 644 /etc/vsftpd.conf
# Exponer puertos para FTP y pasivos
EXPOSE 21 40000-40100

# Comando para iniciar el servidor FTP
CMD ["vsftpd", "/etc/vsftpd.conf"]