FROM debian:latest

RUN apt update && \
    apt install -y iputils-ping net-tools dnsutils nano ftp

# Crear usuario con contraseña
RUN useradd -m user && \
    echo "user:user" | chpasswd && \
    echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
