services:
  rooter:
    build:
      context: .
      dockerfile: Dockerfile.rooter
    container_name: rooter
    command: bash -c "tail -f /dev/null"
    networks:
      svc_net:
        ipv4_address: 172.20.0.10
      prod_net:
        ipv4_address: 172.30.0.10
      dev_net:
        ipv4_address: 172.40.0.10

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev
    ports:
      - "21:21"
    command: bash -c "tail -f /dev/null"
    networks:
      dev_net:
        ipv4_address: 172.40.0.2

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod
    ports:
      - "80:80"
    networks:
      prod_net:
        ipv4_address: 172.30.0.2

  svc:
    build:
      context: .
      dockerfile: Dockerfile.svc
    container_name: svc
    command: bash -c "tail -f /dev/null"
    networks:
      svc_net:
        ipv4_address: 172.20.0.2

networks:
  svc_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
  prod_net:
    ipam:
      config:
        - subnet: 172.30.0.0/24
  dev_net:
    ipam:
      config:
        - subnet: 172.40.0.0/24
