services:
  drupal:
    image: drupal:10-fpm-alpine
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: exampledb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: admindb
    depends_on:
      - db
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    networks:
      - production_net

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    depends_on:
      - drupal
    networks:
      - production_net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: admindb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - production_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - production_net

  drupal2:
    image: drupal:10-apache
    ports:
      - 8082:80
    environment:
      MYSQL_HOST: db2
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    depends_on:
      - db2
    volumes:
      - drupal2_modules:/var/www/html/modules
      - drupal2_profiles:/var/www/html/profiles
      - drupal2_themes:/var/www/html/themes
      - drupal2_sites:/var/www/html/sites
    networks:
      - development_net

  db2:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      - development_net

  adminer2:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    environment:
      ADMINER_DEFAULT_SERVER: db2
    networks:
      - development_net

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
  drupal2_modules:
  drupal2_profiles:
  drupal2_themes:
  drupal2_sites:
  db2_data:

networks:
  vpn_net:
  services_net:
  production_net:
  development_net:
