version: '3.8'

services:

  # Adminer para MySQL
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - server-admin-docker_production_net


  # Adminer para PostgreSQL
  adminer2:
    image: adminer
    container_name: adminer2
    restart: always
    ports:
      - "8081:8080"
    networks:
      - development_net

  # Base de datos MySQL
  db2:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"
    networks:
      - development_net
    volumes:
      - db2_data:/var/lib/mysql

  # Base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - server-admin-docker_production_net

    volumes:
      - db_data:/var/lib/postgresql/data

  # PHP-FPM para PostgreSQL
  web_pgsql_php:
    build: ./services/web_pgsql
    container_name: web_pgsql_php
    networks:
      - server-admin-docker_production_net

    volumes:
      - ./services/web_pgsql/public:/var/www/html
      - ./services/web_pgsql/php-fpm.conf:/usr/local/etc/php-fpm.conf
    depends_on:
      - db

  # Web con Apache y MySQL
  web_mysql:
    build: ./services/web_mysql
    container_name: web_mysql
    depends_on:
      - db2
    ports:
      - "8083:80"
    environment:
      MYSQL_HOST: db2
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./services/web_mysql/public:/var/www/html
    networks:
      - development_net

  # Servidor Nginx para Drupal
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web_pgsql_php
    volumes:
      - ./services/web_pgsql/public:/var/www/html
      - ./services/web_pgsql/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8082:80"
    networks:
      - server-admin-docker_production_net


volumes:
  db_data:
  db2_data:

networks:
  server-admin-docker_production_net:
  development_net:
