pid file = /var/run/rsyncd.pid
log file = /var/log/rsyncd.log
use chroot = no
max connections = 10
timeout = 300
[backup]
path = /backup
comment = Backup de la base de datos de producción
read only = no
list = yes
auth users = root
secrets file = /etc/rsyncd.secrets
